alias l='exa -l --icons --group-directories-first'
alias ls='exa --icons --group-directories-first'
alias la='exa -la --icons --group-directories-first'
alias cat='bat'
alias vi='vim'
alias v='vim'
alias g='git'
alias ..='cd ..'
alias ...='cd ../..'
alias become-postgres='sudo -u postgres -i'
alias npm-ls='npm ls -g --depth=0'
alias docker-killimg='docker rmi $(docker images -a -q)'
alias freespace='df -hH -t ext4'
