# General
export EDITOR=vim

# for Android stuff
export JAVA_HOME=/usr/lib/jvm/default
export ANDROID_SDK_ROOT=~/documents/android
export ANDROID_HOME=~/documents/android

# Rust
export RUST_SRC_PATH=~/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src
export CARGO_HOME=~/.cargo

# NPM
export NPM_CONFIG_PREFIX=~/.node_modules

# for AWS stuff
export AWS_PROFILE=saml
export AWS_DEFAULT_PROFILE=saml

# for Android stuff
export JAVA_HOME=/usr/lib/jvm/default
export ANDROID_SDK_ROOT=~/documents/android
export ANDROID_HOME=~/documents/android

# path
path=("$HOME/.cargo/bin" $path)
path=("$HOME/.node_modules/bin" $path)
path=("$HOME/.emacs.d/bin" $path)
path=("$HOME/.local/bin" $path)
path=("$JAVA_HOME/bin" $path)
path=("$ANDROID_SDK_ROOT/emulator" $path)
path=("$ANDROID_SDK_ROOT/tools" $path)
path=("$ANDROID_SDK_ROOT/platform-tools" $path)
