# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block, everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# vi mode
bindkey -v

# auto complete
autoload -Uz compinit
compinit
zstyle ':completion:*' menu select
setopt COMPLETE_ALIASES

source /home/dale/.dotfiles/zsh/git.zsh

# prompt
SPACESHIP_PROMPT_ORDER=(
  dir           # Current directory section
  git           # Git section (git_branch + git_status)
  line_sep      # Line break
  char          # Prompt character
)
setopt promptsubst
source /usr/share/zsh-theme-powerlevel10k/powerlevel10k.zsh-theme

# aliases
alias l='exa -l --group-directories-first'
alias ls='exa --group-directories-first'
alias la='exa -la --group-directories-first'
alias cat='bat'
alias vi='vim'
alias v='vim'
alias g='git'
alias ..='cd ..'
alias ...='cd ../..'
alias become-postgres='sudo -u postgres -i'
alias npm-ls='npm ls -g --depth=0'
alias docker-killimg='docker rmi $(docker images -a -q)'
alias freespace='df -hH -t ext4'

# load zsh syntax highlight plugin
source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
# load keychain
eval $(keychain --eval --quiet --noask id_rsa)
# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$PATH:$HOME/.rvm/bin"


# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
